development:
  google_analytics_code: <%= ENV['GOOGLE_ANALYTICS_CODE'] %>
  base_url: http://localhost:3000/
  garmin_api_key: af3ee34c5d8ca2b04377d4a9934b4fde


production:
  google_analytics_code: <%= ENV['GOOGLE_ANALYTICS_CODE'] %>
  base_url: <%= ENV['BASE_URL'] %>
  garmin_api_key: <%= ENV['GARMIN_API_KEY'] %>
