development:
  google_analytics_code: <%= ENV['GOOGLE_ANALYTICS_CODE'] %>
  base_url: http://localhost:3000/
  garmin_api_key: 5f0d1111bc2b25273b49e8de6ea853f4


production:
  google_analytics_code: <%= ENV['GOOGLE_ANALYTICS_CODE'] %>
  base_url: <%= ENV['BASE_URL'] %>
  garmin_api_key: <%= ENV['GARMIN_API_KEY'] %>
